package enums;

public enum TipoIncidente {
	VENTO,
	CHUVA,
	NEVOEIRO,
	NEVE,
	GELO_NA_PISTA,
	GRANIZO,
	TRANSITO_PARADO,
	FILAS_DE_TRANSITO,
	TRANSITO_LENTO,
	ACIDENTE_DESCONHECIDO,
	INCIDENTE_DESCONHECIDO,
	TRABALHOS_NA_ESTRADA,
	BLOQUEIO_DE_PISTA,
	BLOQUEIO_DE_ESTRADA
}